<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vim</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^(if|while|for|fu|function|augroup|aug)</string>
	<key>foldingStopMarker</key>
	<string>(endif|endwhile|endfor|endf|endfunction|augroup\.END|aug\.END)$</string>
	<key>name</key>
	<string>VimL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_double</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_single</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_regex</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number_int</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number_hex</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support_function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support_variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support_type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_params</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_call</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expr</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.vim</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*".*$</string>
					<key>name</key>
					<string>comment.line.quotes.viml</string>
				</dict>
			</array>
		</dict>
		<key>expr</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\|\||&amp;&amp;|==(\?|#)?|(!|&gt;|&lt;)=(#|\?)?|(=|!)~(#|\?)?|(&gt;|&lt;)(#|\?)is|isnot|\.|\*|\\|%)</string>
					<key>name</key>
					<string>storage.function.viml</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(fu(n|nction)?|end(f|fu|fun|function)?)\b</string>
					<key>name</key>
					<string>storage.function.viml</string>
				</dict>
			</array>
		</dict>
		<key>function_call</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(([sgbwtl]|)?:?[0-9a-zA-Z_#]+)(?=\()</string>
					<key>name</key>
					<string>support.function.any-method</string>
				</dict>
			</array>
		</dict>
		<key>function_definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*(function)\s*!?\s+(?=(s:)?[0-9a-zA-Z_#]+\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.function.viml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\()</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.viml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.viml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(s:)?[0-9a-zA-Z_#]+</string>
					<key>name</key>
					<string>entity.name.function.viml</string>
				</dict>
			</array>
		</dict>
		<key>function_params</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>-\w+=</string>
					<key>name</key>
					<string>support.type.viml</string>
				</dict>
			</array>
		</dict>
		<key>inline_comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.vim</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?!\$)(")(?!\{).*$\n?</string>
					<key>name</key>
					<string>comment.line.quotes.viml</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|while|for|return|end(if|for|while)?|au(g|group)|else(if|)?|do|in|:)\b</string>
					<key>name</key>
					<string>keyword.control.viml</string>
				</dict>
			</array>
		</dict>
		<key>number_hex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#[0-9a-f]{6}</string>
					<key>name</key>
					<string>constant.numeric.hex</string>
				</dict>
			</array>
		</dict>
		<key>number_int</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>-?\d+</string>
					<key>name</key>
					<string>constant.numeric.integer</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_double</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>"(\\\\|\\"|[^\n"])*"</string>
					<key>name</key>
					<string>string.quoted.double.viml</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_single</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>'(\\\\|\\'|[^\n'])*'</string>
					<key>name</key>
					<string>string.quoted.single.viml</string>
				</dict>
			</array>
		</dict>
		<key>string_regex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>/(\\\\|\\/|[^\n/])*/</string>
					<key>name</key>
					<string>string.regexp.viml</string>
				</dict>
			</array>
		</dict>
		<key>support_function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(set(local|global)?|let|command|filetype|colorscheme|\w*map|syn|exe(c|cute)?|ec(ho|)?|au(tocmd|)?)\b</string>
					<key>name</key>
					<string>support.function.viml</string>
				</dict>
			</array>
		</dict>
		<key>support_type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&lt;.*?&gt;</string>
					<key>name</key>
					<string>support.type.viml</string>
				</dict>
			</array>
		</dict>
		<key>support_variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(am(enu|)?|(hl|inc)?search|[Bb]uf([Nn]ew[Ff]ile|[Rr]ead)?|[Ff]ile[Tt]ype)\b</string>
					<key>name</key>
					<string>support.variable.viml</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([sSgGbBwWlLaAvV]:|@|$|&amp;(?!&amp;))\w*</string>
					<key>name</key>
					<string>variable.other.viml</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.viml</string>
	<key>uuid</key>
	<string>0555180C-1AF8-4D94-9937-4434C2AE07E5</string>
</dict>
</plist>
