set nocompatible              " Not compatible with vi
filetype off                  " required

" Load vim-plug from the tracked submodule and initialise it.
source ~/.vim/bundle/vim-plug/plug.vim
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive' " Git Wrapper
Plug 'editorconfig/editorconfig-vim' " .editorconfig support
if has('nvim')
  Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
endif
" Themes
Plug 'catppuccin/nvim', { 'branch': 'vim', 'as': 'catppuccin' }

call plug#end()
filetype plugin indent on    " required

set clipboard=unnamed " Make vim use system keyboard

set tabstop=2 shiftwidth=2 expandtab " Set TAB to two spaces
set number " Enable line numbers
set mouse=a " Enable mouse integration

" Syntax & Coloring
syntax enable

" Enable colors
set t_Co=256
set termguicolors
let $NVIM_TUI_ENABLE_TRUE_COLOR=1 " Neovim only
set guicursor=

colorscheme catppuccin-nvim

" Keybindings
map <F7> mzgg=G`z " Reindent entire file

" Functions
command W silent execute 'write !sudo tee ' . shellescape(@%, 1) . ' >/dev/null'

let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
au FileType gitcommit let b:EditorConfig_disable = 1
