set nocompatible              " Not compatible with vi
filetype off                  " required

" Add Vundle to Runtime and Initialise
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle/plugins')
Plugin 'VundleVim/Vundle.vim' " Vundle Plugin Manager
Plugin 'tpope/vim-fugitive' " Git Wrapper
Plugin 'L9' " Vim Script & Plugin Library

" Themes
Plugin 'mhartington/oceanic-next'
call vundle#end()            " required
filetype plugin indent on    " required

set clipboard=unnamed " Make vim use system keyboard

set tabstop=2 shiftwidth=2 expandtab " Set TAB to two spaces
set number " Enable line numbers

" Syntax & Coloring
syntax enable

" Enable colors
set t_Co=256
let $NVIM_TUI_ENABLE_TRUE_COLOR=1 " Neovim only

colorscheme OceanicNext
set background=dark

" Keybindings
map <F7> mzgg=G`z " Reindent entire file
