set nocompatible              " Not compatible with vi
filetype off                  " required

" Add Vundle to Runtime and Initialise
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle/plugins')
Plugin 'gmarik/Vundle.vim' " Vundle Plugin Manager
Plugin 'tpope/vim-fugitive' " Git Wrapper
Plugin 'L9' " Vim Script & Plugin Library
call vundle#end()            " required
filetype plugin indent on    " required

set clipboard=unnamed " Make vim use system keyboard

set tabstop=2 shiftwidth=2 expandtab " Set TAB to two spaces
set number " Enable line numbers

" Syntax & Coloring
colorscheme deepsea
syntax on

" Keybindings
map <F7> mzgg=G`z " Reindent entire file
