---
- name: Stat Atuin config file
  stat:
    path: "{{ ansible_facts.env.HOME }}/.config/atuin/config.toml"
  register: atuin_config_stat

- block:
  - name: Unique Atuin session history
    ini_file:
      path: "{{ ansible_facts.env.HOME }}/.config/atuin/config.toml"
      option: "filter_mode_shell_up_key_binding"
      value: '"session-preload"'
  when: atuin_config_stat.stat.exists

- name: Stat Ghostty config file
  stat:
    path: "{{ ansible_facts.env.HOME }}/Library/Application Support/com.mitchellh.ghostty/config"
  register: ghostty_config_stat

- block:
  - name: Configure Ghostty
    ini_file:
      path: "{{ ansible_facts.env.HOME }}/Library/Application Support/com.mitchellh.ghostty/config"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
      mode: "0644"
    with_items:
      # pass our TERM info to older SSH hosts which may not have it
      - option: "shell-integration-features"
        value: "true"

      # switch between light and dark with the system
      # https://github.com/ghostty-org/ghostty/discussions/5437
      - option: "theme"
        value: "dark:Catppuccin Frappe, light:Catppuccin Latte"
    notify: Reload Ghostty
  when:
    - ansible_facts.os_family == "Darwin"
    - ghostty_config_stat.stat.exists

- name: Stat Karabiner directory
  stat:
    path: "{{ ansible_facts.env.HOME }}/.config/karabiner/"
  register: karabiner_dir_stat

- block:
  - name: Find Karabiner complex modification rules
    find:
      paths: "{{ dotfiles_dir }}/karabiner/complex_modifications"
      file_type: file
    register: karabiner_complex_modification_rules

  - name: Link Karabiner complex modification rules
    file:
      src: "{{ item.path }}"
      dest: "{{ ansible_facts.env.HOME }}/.config/karabiner/assets/complex_modifications/{{ item.path | basename }}"
      state: link
      force: yes
    loop: "{{ karabiner_complex_modification_rules.files }}"

  - name: Find Karabiner complex modification symlinks
    find:
      paths: "{{ ansible_facts.env.HOME }}/.config/karabiner/assets/complex_modifications"
      file_type: link
    register: karabiner_complex_modification_links

  - name: Stat Karabiner complex modification symlinks
    stat:
      path: "{{ item.path }}"
      follow: false
    loop: "{{ karabiner_complex_modification_links.files }}"
    register: karabiner_complex_modification_link_stats

  - name: Stat Karabiner complex modification symlink targets
    stat:
      path: "{{ item.stat.lnk_source }}"
    loop: "{{ karabiner_complex_modification_link_stats.results }}"
    register: karabiner_complex_modification_link_target_stats
    when:
      - item.stat.islnk | default(false)
      - item.stat.lnk_source is defined
      - item.stat.lnk_source | dirname == dotfiles_dir ~ '/karabiner/complex_modifications'

  - name: Remove dead Karabiner complex modification symlinks
    file:
      path: "{{ item.item.stat.path }}"
      state: absent
    loop: "{{ karabiner_complex_modification_link_target_stats.results | rejectattr('skipped', 'defined') }}"
    when:
      - not item.stat.exists

  when:
    - ansible_facts.os_family == "Darwin"
    - karabiner_dir_stat.stat.isdir | default(false)
