# if rbenv is present, configure it for use
# if which rbenv &> /dev/null; then
if [ -d $HOME/.rbenv ]; then
    # Put the rbenv entry at the front of the line
    export PATH="$HOME/.rbenv/bin:$PATH"

    # enable shims and auto-completion
    eval "$(rbenv init -)"
fi

# Add RVM to PATH for scripting, if rvm is present
if which rvm-prompt &> /dev/null; then
    export PATH=$HOME/.rvm/bin:$PATH
fi
