export PATH="$HOME/bin:$PATH:/opt/local/bin"

# if rbenv is present, configure it for use
if [ -d $HOME/.rbenv ]; then
  export PATH="$HOME/.rbenv/bin:${PATH}"
  eval "$(rbenv init -)"
fi

# Add RVM to PATH for scripting, if rvm is present
if which rvm-prompt &> /dev/null; then
  export PATH="$HOME/.rvm/bin:$PATH"
fi

# If Jenv exists, add it to PATH and init
if [ -d $HOME/.jenv ]; then
  export PATH="$HOME/.jenv/bin:$PATH"
  eval "$(jenv init -)"
fi

# Node Project Manager Init
if which npm &> /dev/null; then
  eval "$(npm completion -)"
fi

# Node Version Manager
if [ -d $HOME/.nvm ]; then
  source $HOME/.nvm/nvm.sh
fi
