[ -z "$SSH_CONNECTION" ] && ZSH_TMUX_AUTOSTART="true"
ZSH_AUTOSUGGEST_USE_ASYNC="tue"

# Add Antigen
source ~/.zsh/antigen/antigen.zsh
antigen use oh-my-zsh # Add Oh-My-ZSH as an API for plugins and theme

antigen bundles <<EOBUNDLES
command-not-found
colored-man-pages
magic-enter
extract
tmux
git

zsh-users/zsh-completions
zsh-users/zsh-autosuggestions
zsh-users/zsh-syntax-highlighting
HeroCC/LS_COLORS

rupa/z
EOBUNDLES
antigen theme romkatv/powerlevel10k
source $HOME/.zsh/themes/p10k-lean.zsh
#antigen theme $HOME/.zsh/themes bira-cust --no-local-clone
antigen apply # Use it

# Source all the configs
source ~/.zsh/history.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/exports.zsh
if [ -e "$HOME/.zsh/local.zsh" ]; then # If local.zsh exists, source it
  source ~/.zsh/local.zsh
fi
